# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  poem: false
  collapse_walkthrough: true
  sequence_diagrams: false
  auto_review:
    auto_incremental_review: false
    base_branches:
      - master
  pre_merge_checks:
    docstrings:
      mode: 'off'
  tools:
    github-checks:
      enabled: true
      timeout_ms: 100000
code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: "*.{c,h}"
        instructions: Use Asterisk style docstrings with Args and Returns sections in the QT format.
chat:
  art: false
