# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  collapse_walkthrough: true
  sequence_diagrams: false
  auto_review:
    auto_incremental_review: false
    base_branches:
      - master
  pre_merge_checks:
    docstrings:
      mode: 'off'
  tools:
    github-checks:
      timeout_ms: 100000
chat:
  art: false
