--- a/res/Makefile
+++ b/res/Makefile
@@ -78,6 +78,8 @@
 res_parking.o: _ASTCFLAGS+=$(AST_NO_FORMAT_TRUNCATION)
 snmp/agent.o: _ASTCFLAGS+=-fPIC
 res_snmp.o: _ASTCFLAGS+=-fPIC
 
+res_usbradio.so: LIBS+=-lusb -lasound -lportaudio
+
 MODULE_EXCLUDE=ENABLE_SRTP_AES_192 ENABLE_SRTP_AES_256 ENABLE_SRTP_AES_GCM
 
