diff --git a/channels/Makefile b/channels/Makefile
index 0f8d1328c5..c9523f6d69 100644
--- a/channels/Makefile
+++ b/channels/Makefile
@@ -22,6 +22,9 @@ include $(ASTTOPDIR)/Makefile.moddir_rules
 $(call MOD_ADD_C,chan_iax2,$(wildcard iax2/*.c))
 iax2/parser.o: _ASTCFLAGS+=$(call get_menuselect_cflags,MALLOC_DEBUG)
 
+chan_simpleusb.so: LIBS+=-lusb -lasound
+chan_usbradio.so: LIBS+=-lusb -lasound
+
 $(call MOD_ADD_C,chan_pjsip,$(wildcard pjsip/*.c))
 $(call MOD_ADD_C,chan_dahdi,$(wildcard dahdi/*.c) sig_analog.c sig_pri.c sig_ss7.c)
 
