;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;; Toggle GPIO (pin 1) when audio clipping detected  ;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;MENU:clip-led-gpio1:Assert GPIO (pin 1) when audio clipped

[clip-led-gpio1](!)

clipledgpio = 1              ; Enable ADC Clip Detect feature to use a GPIO output (0 to disable).
                             ; Supports URI Clip LED by setting a GPIO (if available) high for 500mS
                             ; when clipping detected. Value = GPIO# to use (GPIO1 recommended)

