;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;; SHARI (SA818 Ham Allstar Radio Interface) ;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;MENU:shari-pihat:SHARI PiHat
;
; defaults for SHARI PiZero
;
[shari-pihat](!)
plfilter = no
ctcssfrom = no

;MENU:shari-pizero:SHARI PiZero
;
; defaults for SHARI PiZero
;
[shari-pizero](!)
plfilter = no
ctcssfrom = no

