;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;; SkywarnPlus ;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;MENU:SkywarnPlus:SkywarnPlus courtesy tones

[telemetry-SkywarnPlus](telemetry)

ct1 = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct1
ct2 = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct2
;ct3 = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct3
;ct4 = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct4
;ct5 = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct5
;ct6 = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct6
remotetx = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct1
remotemon = /usr/local/bin/SkywarnPlus/SOUNDS/TONES/ct1

[SkywarnPlus](!)

linkunkeyct = ct2
remotect = ct1
unlinkedct = ct1

tailmessagelist = /tmp/SkywarnPlus/wx-tail
tailmessagetime = 1800000
tailsquashedtime = 120000

telemetry=telemetry-SkywarnPlus

