diff --git a/utils/Makefile b/utils/Makefile
index a17a3c1d39..5e8e4e241d 100644
--- a/utils/Makefile
+++ b/utils/Makefile
@@ -27,7 +27,7 @@ ASTTOPDIR?=..
 #     changes are made to ast_expr2.y or ast_expr2.fl (or the corresponding .c files),
 #     as a regression test. Others (mere mortals?) need not bother, but they are
 #     more than welcome to play! The regression test itself is in expr2.testinput.
-ALL_UTILS:=$(MENUSELECT_UTILS)
+ALL_UTILS:=$(MENUSELECT_UTILS) simpleusb-tune-menu radio-tune-menu
 UTILS:=$(ALL_UTILS)
 
 LIBS += $(BKTR_LIB) # astobj2 with devmode uses backtrace
