#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# Test clang-format
git clang-format --style=file:./.dev/.clang-format --staged -q

# Check if any files were reformatted by git clang-format
CHANGED_FILES=$(git diff --name-only )

# Redirect output to stderr.
exec 1>&2

if [ -n "$CHANGED_FILES" ]
then
    echo "Staged files were auto-formatted by clang-format. Please review the changes and stage the files again."
    # Add the reformatted files back to the staging area
    #git add $CHANGED_FILES
    exit 1
fi

codespell --skip "./.git" --ignore-words ./.dev/.codespellignore --write-changes

exec 1>&2

# Check if any files were reformatted by git clang-format
CHANGED_FILES=$(git diff --name-only )

if [ -n "$CHANGED_FILES" ]
then
   echo "Spelling errors!"
   echo "Run codespell"
   echo $codespell
   exit 1
fi

