# This is a basic workflow that is manually triggered

name: Run codespell on source code

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run codespell on source code
      uses: codespell-project/actions-codespell@v2
      with:
          exclude_file: include/*
          ignore_words_file: .codespellignore
          
